### ISSUE TITLE
Lvl 9

### ISSUE THREAD

**Issue by Ikonedesign** [starvingcats/Leyla#12]
We still need the final Level 9.
Refer to the storyboard to build it.

![lvl9 storyboard](https://user-images.githubusercontent.com/50525155/73304646-f416ba80-4218-11ea-98f2-98741d3f64d6.png)

- [ ] Level 9

**Comment by gandie** [comment]
@Ikonedesign  Telescope is part of `lvl9_background.png` background, making interaction some kind of difficult.
I'll ignore this and add an interactable telescope ( from lvl3 ), so you may remove the background telescope.

**Comment by Ikonedesign** [comment]
ok, my fault, but an easy fix. thank you!

**Comment by gandie** [comment]
Done 0a39207cd836d9c710223d5aaf763bb328c66ff9
