### ISSUE TITLE
Chapter 5: Text too early

### ISSUE THREAD

**Issue by jhinghaus** [starvingcats/Leyla#14]
**Describe the bug**
When talking to the lady in chapter five the text about the lamps at the high window appears before you can see the lamps.

**To Reproduce**
Go to chapter 5 and talk to the lady.

**Expected behavior**
I would expect the line about the lamps, when the lights at the window come into sight.

**Comment by Ikonedesign** [comment]
We already have those text positioning issues collected here: [https://github.com/starvingcats/Leyla/issues/13](url)
Feel free to add smaller issues like this into the list there.
Thank you for the feedback.
