### ISSUE TITLE
Chapter 6 and 8: Texts befor you can see what it's about

### ISSUE THREAD

**Issue by jhinghaus** [starvingcats/Leyla#15]
**Describe the bug**
The starting text appears before you can see the lamps Leyla is talking about.

**To Reproduce**
Go to that chapter.

**Expected behavior**
I would except the text triggered when you made a few steps and can see the thinks Leyla is talking about.

**Comment by Ikonedesign** [comment]
We already have those text positioning issues collected here: [https://github.com/starvingcats/Leyla/issues/13](url)
Feel free to add smaller issues like this into the list there.
Thank you for the feedback.
