### ISSUE TITLE
Talking about a bus stop at the other end of the level

### ISSUE THREAD

**Issue by jhinghaus** [starvingcats/Leyla#16]
**Describe the bug**
In chapter 8 Leyla talks about the bus stop when standing on the left side of the level.
The stop is on the right.

**To Reproduce**
Go to chapter 8 and click though the text.

**Expected behavior**
Either the text should be triggered, when Leyla arrives near the stop, or the text should indicate that she talks about something she can see in the distance.

**Comment by Ikonedesign** [comment]
We already have those text positioning issues collected here: [https://github.com/starvingcats/Leyla/issues/13](url)
Feel free to add smaller issues like this into the list there.
Thank you for the feedback.
