### ISSUE TITLE
Glitches

### ISSUE THREAD

**Issue by Ikonedesign** [starvingcats/Leyla#20]
When loading a new level, sometimes a bit of text appears to the left of the playscreen, sometimes remaining, sometimes not. Use the screenshot below as reference.

![Bildschirmfoto 2020-03-25 um 19 54 39](https://user-images.githubusercontent.com/50525155/77575642-228cdb00-6ed4-11ea-9f19-2fb53bedd6d2.png)

Also in Lvl 8 it's possible that leyla doesn't appear and you have to reload to properly play the level.

**Comment by gandie** [comment]
Fixed
