### ISSUE TITLE
Audio for the intro

### ISSUE THREAD

**Issue by jhinghaus** [starvingcats/Leyla#23]
We can not play an audio on the start page before the user has interacted with the page. Browsers (and users) don't like that.
If you could make an audio button or symbol for the start page, I could hook the audio output on it.

**Comment by gandie** [comment]
There you go 4e984bafabf3d0f073f024839286616036fede80

**Comment by gandie** [comment]
Intro audio hooked in 68e9d18e848ed00d926b88b4f512f04e86f2cea9
I like the simple sound_helper implementation btw 😃
