### ISSUE TITLE
Build levels

### ISSUE THREAD

**Issue by Ikonedesign** [starvingcats/Leyla#3]
Use the storyboard for reference
- [x] Level 1 Intro

- [x]  interaction with telescope

- [x]  telescope splashscreen

- [x] Level 2 Entering the city
- [x]  driving the car
- [x]  sidescrolling
- [ ] (parallax)

- [x] Level 3 New Home
- [x] interaction with telescope
- [x] starless splashscreen
- [ ]  enter the house, indoor sublevel
- [ ]  shut the indoor light

- [x] Level 4 Moths
- [x]  toggle light on/off
- [ ]  (toggle enables timed motion detector)
- [x]  switching of the light disperses moth swarm

- [x] Level 5 Billboard
- [x]  pickup lights from the bottom of the billboard
- [x]  place them on top

- [x] Level 6 Monument
- [x]  make pivotable lights
- [x]  lights need to be adjusted to hit only the monument

**Comment by gandie** [comment]
File layout is done, levels will follow step by step

**Comment by gandie** [comment]
All levels done so far. Plz specify in more detaill

**Comment by gandie** [comment]
Plz add lvl 7 and 8

**Comment by gandie** [comment]
**Technical note:**

To solve the problem of memorizing things done in sublevels i'll use this:

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Local_storage

...which is surprisingly compatible across browsers...

https://caniuse.com/#search=localStorage

**Comment by gandie** [comment]
Still needing new storyboards, assets and detailed level specifications.... :kissing:
