### ISSUE TITLE
Textbox

### ISSUE THREAD

**Issue by Ikonedesign** [starvingcats/Leyla#4]
Leyla needs a textbox to express thoughts and dialoques with npc's.
This textbox should be placed close to the top edge of the screen.
An editable text file to fill in the text into the box would be nice.

- [x] Textbox
- [x] Textfile

![ArtBoard2_2](https://user-images.githubusercontent.com/50525155/70440161-da1af000-1a91-11ea-8cbe-32999f09dba5.png)

**Comment by gandie** [comment]
Done with badfc3e4dc4017b4cc57e9a747e92e5f01f71319
Feel free to use `www/json/dialogues.json` to alter content of textboxes urself. Skip through using the F key while ingame.
Plz check and close

**Comment by Ikonedesign** [comment]
Changing dialogues in www/json/dialogues.json does not work.
In addition, the textbox should be fixed instead of scrolling along with the background like in the car level.

**Comment by gandie** [comment]
That's a classic one...i forgot to mention. Your browser tries to cache as much content as possible including the `www/json/dialogues.json` file fetched in the `preload` function. Depending on your browser there's a shortcut to enforce reloading cached contents, `CTRL-SHIFT-R` in chrome and firefox. I will write some lines to avoid caching code-side, shouldn't be that hard...

So i see two tasks here:
+ Avoid browser caching dialogues
+ In levels using the virtual camera the dialog boxes must be placed relative to the gamechar

Challenge accepted!

**Comment by gandie** [comment]
Both tasks done (hopefully):
+ Browser caching 39d5f7c09d8bd99b84a
+ Textbox position 421f22526dcd3be0

**Comment by gandie** [comment]
I assume textboxes are ready for usage.
