### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by gandie** [starvingcats/Leyla#6]
When the game starts you do not know how to control the game.

We should add a welcome screen like "This is Leyla, a game about light pollution. Here's a short description on how to control Leyla..."

Alternatively the welcome screen may only contain a banner and the controls and stuff are described via textboxes in the first level.

**Comment by gandie** [comment]
#7 preparations done. We can now start working on this

**Comment by Ikonedesign** [comment]
I just added a startscreen, implement it and we can close this issue.

**Comment by gandie** [comment]
Nice one, will do so in the next evenings!

**Comment by gandie** [comment]
Job's done: 8bc26604009b491d4264ba229ef242f9a18ab3a8
