### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by gandie** [starvingcats/Leyla#7]
The resolution of the game is quite poor and must be raised. Additionally we must switch to 16:9 format.

First step should be a quick&dirty replacement of the values `createCanvas` is called with. This will lead to a bunch of img path corrections in all levels and is therefore a good chance to define a naming pattern for graphics used ingame.

In order to make graphics paths as retainable as possible (and allow/simplify batch processing of images) i suggest something like:

`lvl1_background.png`
`lvl3_lamp_on.png`

All lower case, no spaces. `[<levelnum>_]<objectname>[_<optional suffix>].png`

Allowed suffixes may be `on`, `off` and stuff to describe the state of an object or a number to tell these pictures must be used in an animation. As an example the moths used in lvl4 may be named:
`lvl4_moths_1.png` , `lvl4_moths_2.png` ....

The levelnum prefix may be omitted to indicate these images may be used in general, e.g. :
`leylawalk_1.png` , `leylawalk_2.png` ...

@Ikonedesign : Pattern agreed? Will do the initial renaming-orgy on-the-fly when reworking on higher resolution... :wink: 

This issue must be solved before work on #6 can be done without resolution hazzle.

**Comment by gandie** [comment]
JS Code work has been done in e6b0a9b168ef4e368f912379aa8a22801f418a06 .
Resolution is switchable in `leyla_js_helper.js`

**Comment by Ikonedesign** [comment]
Looks nice so far, no complaints. I will provide new assets asap.
