### ISSUE TITLE
Better dialogues / texts

### ISSUE THREAD

**Issue by gandie** [starvingcats/Leyla#8]
Current texts in dialogue boxes are just examples for testing purposes.

These texts must be replaced with something more useful / informative
.
If more chapters are needed they must be called in the corresponding JS code of the level. Feel free to ask for such chapters, i will add calls in JS code (or explain how to do this) if u provide an event description on when to show the new chapter.

**Comment by jhinghaus** [comment]
Do the dialogues have to be in english or german?

**Comment by Ikonedesign** [comment]
Yes, i'm already writing them and will push them later.
